name: Google Indexing

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Google Indexing
        uses: robingenz/google-indexing-action@main
        with:
          siteUrl: 'manofmystery1981.github.io'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
